### ISSUE TITLE
Get this text whenever I press TAB

### ISSUE THREAD

**Issue by Vaimer9** [artart222/CodeArt#18]
Getting this text whenever I press TAB in insert mode
```
<Plug>(cmp.utils.keymap.recursive:    )
```

**Comment by artart222** [comment]
You mean it will added to your buffer?

**Comment by Vaimer9** [comment]
yeah not at the bottom, it gets added to wherever im writing

**Comment by artart222** [comment]
Did you change something in your maps.lua file? I think the problem is there because my CodeArt configs are up to date with repo configs and there is no problem in it.

**Comment by Vaimer9** [comment]
It was working fine and then suddenly this happened, im gonna check the file anyways one sec

**Comment by Vaimer9** [comment]
anything specific I should look for?

**Comment by artart222** [comment]
Can I answer you another time in this day? I have online school right now.

**Comment by Vaimer9** [comment]
I was programming rn im just gonna use vsc for now :( reply if ur free

**Comment by artart222** [comment]
Ok. I have class right now after class I will look for your problem

**Comment by artart222** [comment]
Can you search in your NeoVim configs directory with `:Telescope live_grep` for cmp.utils.keymap.recursive
If you find something please share that file with pastebin here

**Comment by Vaimer9** [comment]
live_grep doesn't seem to work so I just used traditional `grep`
using `grep -i -R 'cmp.utils.keymap.recursive' .`, unfortunately I got no results

**Comment by Vaimer9** [comment]
I am thinking abou uninstalling CodeArt as I had almost the same config if not better earlier and im just getting errors a lot mostly due to my mistakes in .lua file, I had tried uninstalling but had ran into problems earlier, is there any official way of uninstall?

**Comment by artart222** [comment]
No but you can look at your OS installer file in (CodeArt/insaller/your_os.py) and uninstall dependencies one by one with looking at main function

**Comment by artart222** [comment]
Just I want to say something

**Comment by artart222** [comment]
I fixed `:CodeArtUpdate` on macOS and linux and make it for windows. You can update CodeArt maybe your error fixed

**Comment by artart222** [comment]
If you want to delete CodeArt I just want to say thanks for your opening issues in time you used CodeArt. it helped development process

**Comment by Vaimer9** [comment]
I ran the Update command but the problem still persisted, as much as I want to keep using CodeArt all the problems Im getting keep interfering when im productive and in the end nvim is for development what good if I can't do that. Would surely recommend codeArt to other people :)

**Comment by Vaimer9** [comment]
reinstalled nvim and after I press `i` im getting this error:
![image](https://user-images.githubusercontent.com/81609819/140017597-5a1e5a5d-1192-45bd-9398-d0a1b2be5686.png)
If this has anything to do with CodeArt please let me know otherwise Im just going to close the issue

**Comment by artart222** [comment]
Run packer `:PackerSync`

**Comment by artart222** [comment]
After that restart NeoVim

**Comment by artart222** [comment]
What happend?

**Comment by Vaimer9** [comment]
lemme run it

**Comment by Vaimer9** [comment]
I dont have Packer, I use Plug as my daily driver, I ran pluginstall and all the extensions run fine just get this error whenever I press `i`

**Comment by Vaimer9** [comment]
Is there a way of supressing this error as I don't think that I am getting any actual problems just the error

**Comment by artart222** [comment]
You must use packer!

**Comment by artart222** [comment]
I lazy loaded plugins

**Comment by artart222** [comment]
Your error is because nvim-cmp is not loaded. If you use packer you can choose to load plugins on specific event

**Comment by artart222** [comment]
nvim-cmp will load whenever you go to insert mode

**Comment by Vaimer9** [comment]
Installing Packer

**Comment by Vaimer9** [comment]
Never had this prob before any way of disabling nvim-cmp?

**Comment by Vaimer9** [comment]
One sec I did smth very stupid need to reinstall nvim wont take too long

**Comment by artart222** [comment]
I installed CodeArt on new ubuntu virtual machine. It is working fine. I don't have your problem with pressing `Tab`

**Comment by Vaimer9** [comment]
I made it work, I will surely download in the future but not right now thank you for all the quick replies hope this plugin blow up :)

**Comment by artart222** [comment]
Thanks
